### PR TITLE
Update dependencies to make the package work with latest node/io

### LINKED ISSUE #110: Fails to install with iojs@3.0.0
I'm being unable to install jsonld with iojs@3.0.0, it seems that the problem with contextify (https://github.com/digitalbazaar/jsonld.js/issues/86) is back or still present:

```
/Users/david/.node-gyp/3.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:159:16: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::Value>' requested here
        return NanEscapeScope(NanNew<Context>(
               ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/contextify.cc:1:
In file included from /Users/david/.node-gyp/3.0.0/include/node/node.h:42:
/Users/david/.node-gyp/3.0.0/include/node/v8.h:7070:3: error: assigning to 'v8::Integer *volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/david/.node-gyp/3.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:211:13: note: in instantiation of function template specialization 'v8::ReturnValue<v8::Integer>::Set<v8::Value>' requested here
            NanReturnValue(NanNew<Integer>(None));
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
In file included from ../src/contextify.cc:1:
In file included from /Users/david/.node-gyp/3.0.0/include/node/node.h:42:
/Users/david/.node-gyp/3.0.0/include/node/v8.h:7070:3: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/david/.node-gyp/3.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:225:13: note: in instantiation of function template specialization 'v8::ReturnValue<v8::Boolean>::Set<v8::Value>' requested here
            NanReturnValue(NanNew<Boolean>(false));
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
In file included from ../src/contextify.cc:1:
In file included from /Users/david/.node-gyp/3.0.0/include/node/node.h:42:
/Users/david/.node-gyp/3.0.0/include/node/v8.h:7070:3: error: assigning to 'v8::Array *volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/david/.node-gyp/3.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:236:13: note: in instantiation of function template specialization 'v8::ReturnValue<v8::Array>::Set<v8::Value>' requested here
            NanReturnValue(blank);
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
14 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
```

### PR DESCRIPTION
**Pull request by yamalight**
Update of the dependencies to make the package work with latest node/io (v3.x and v4.x).
Will close #110

### CODE REVIEW

**Comment by dlongley** [comment]
Unfortunately, jsdom 4.0+ doesn't work with node 0.10 or node 0.12. Until we separate the RDFa parser from this package (which we should, see: #98), we can't upgrade jsdom past 3.x.

**Comment by yamalight** [comment]
@dlongley why not publish it as next major version and backport fixes (which would be trivial since difference is only in deps versions) when needed to older version? (e.g. 0.3.x for pre 3.0 and 0.4.x for 3.0+)

**Comment by dlongley** [comment]
@yamalight, I was holding out hope to cut the RDFa stuff out entirely before jumping to the next version. That way we only have to deal with two versions instead of three ... as we'll have to bump versions again once we move RDFa support to a separate package. We may do that (what you suggest) anyway, because we haven't had time (and there have been no PRs) to split RDFa out of the package in a long while.

**Comment by yamalight** [comment]
@dlongley did I get it correctly that the only part that uses RDFa is `jsonld.request = require('./request');`? If yes, then it should be pretty easy to split that into separate optional module, right? If not, I'll dig in a bit more tomorrow.

If this split will speed up the update to 4.0.0, I'm willing to do this over tomorrow and send a PR, since we're depending on this module too much :)

**Comment by dlongley** [comment]
@yamalight, I'm going to cc @davidlehn to provide more details on splitting stuff out. Since he worked on the RDFa integration stuff he'll have a better idea of how easy it should be than me.

**Comment by davidlehn** [comment]
I split request extension into https://github.com/digitalbazaar/jsonld-request and cli tool into https://github.com/digitalbazaar/jsonld-cli.  If you just need to core jsonld lib, this may fix dependency issues.

**Comment by yamalight** [comment]
@davidlehn yep, works great now, thanks!
I'll close the PR since it's not needed anymore.
